# Generated by Django 6.1 on 2026-09-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Wema Bank', max_length=150)),
                ('account_name', models.CharField(default='Naturale May Business Enterprise', max_length=150)),
                ('account_number', models.CharField(default='0423979574', max_length=50)),
                ('whatsapp_number', models.CharField(default='2347037305041', max_length=30)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(default='46 Aba-Owerri Road, close to Brass Junction, Aba')),
                ('payment_instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
