# Generated by Django 6.1 on 2026-08-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_display',
            field=models.CharField(choices=[('price', 'Show Price'), ('contact', 'Contact for Price'), ('coming_soon', 'Coming Soon')], default='price', max_length=20),
        ),
    ]
