"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information:
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings:
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env explicitly from the project root
ENV_FILE = BASE_DIR / ".env"
load_dotenv(ENV_FILE, override=True)
# ---------------------------------------------------------
# Build paths
# ---------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------
# Security / Debug
# ---------------------------------------------------------

# Never hard-code this value. Set SECRET_KEY in .env locally and in the
# Railway service variables for production.
SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY environment variable is not set."
    )


# DEBUG defaults to False for production safety.
# DEBUG defaults to False for production safety.

DEBUG = os.getenv("DEBUG", "False").lower() == "true"


# ---------------------------------------------------------
# Allowed hosts
# ---------------------------------------------------------

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]

# Railway supplies this hostname at runtime. Custom domains should still be
# added explicitly through the ALLOWED_HOSTS environment variable.
RAILWAY_PUBLIC_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN")
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)


# ---------------------------------------------------------
# CSRF trusted origins
# ---------------------------------------------------------

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]

if RAILWAY_PUBLIC_DOMAIN:
    railway_origin = f"https://{RAILWAY_PUBLIC_DOMAIN}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)


# ---------------------------------------------------------
# Application definition
# ---------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "core",
    "products",
    "services",
    "appointments",
    "contact",
    "owner",
]


# ---------------------------------------------------------
# Middleware
# ---------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ---------------------------------------------------------
# URLs
# ---------------------------------------------------------

ROOT_URLCONF = "config.urls"


# ---------------------------------------------------------
# Templates
# ---------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ---------------------------------------------------------
# WSGI
# ---------------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"


# ---------------------------------------------------------
# Database
# ---------------------------------------------------------

# Locally:
#     SQLite will be used automatically.
#
# Production:
#     If DATABASE_URL exists, it will be used instead.
#
# Example:
# DATABASE_URL=postgresql://user:password@host:5432/database

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# ---------------------------------------------------------
# Email
# ---------------------------------------------------------

# Django 6.1 MAILERS configuration.
#
# Production should use SMTP.
# All credentials come from environment variables.

MAILERS = {
    "default": {
        "BACKEND": os.getenv(
            "EMAIL_BACKEND",
            "django.core.mail.backends.smtp.EmailBackend",
        ),

        "HOST": os.getenv(
            "EMAIL_HOST",
            "",
        ),

        "PORT": int(
            os.getenv(
                "EMAIL_PORT",
                "587",
            )
        ),

        "USERNAME": os.getenv(
            "EMAIL_HOST_USER",
            "",
        ),

        "PASSWORD": os.getenv(
            "EMAIL_HOST_PASSWORD",
            "",
        ),

        "USE_TLS": os.getenv(
            "EMAIL_USE_TLS",
            "True",
        ).lower() == "true",

        "USE_SSL": os.getenv(
            "EMAIL_USE_SSL",
            "False",
        ).lower() == "true",
    }
}


# ---------------------------------------------------------
# Default email settings
# ---------------------------------------------------------

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "Natural May <noreply@example.com>",
)

SERVER_EMAIL = os.getenv(
    "SERVER_EMAIL",
    DEFAULT_FROM_EMAIL,
)


# ---------------------------------------------------------
# Password validation
# ---------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation."
        "MinimumLengthValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation."
        "CommonPasswordValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation."
        "NumericPasswordValidator",
    },
]


# ---------------------------------------------------------
# Internationalization
# ---------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------
# Static files
# ---------------------------------------------------------

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# ---------------------------------------------------------
# Media files
# ---------------------------------------------------------

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ---------------------------------------------------------
# Storage
# ---------------------------------------------------------

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND":
        "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ---------------------------------------------------------
# Security settings
# ---------------------------------------------------------

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# During automated tests, HTTPS redirects interfere with Django's
# test client. Production keeps the secure settings enabled.
IS_TESTING = os.getenv("DJANGO_TEST", "").lower() == "true"

# Detect Django test environment
TESTING = os.getenv("DJANGO_TEST", "").lower() == "true"

# HTTPS security settings
# Disabled during automated tests because Django's test client
# does not make HTTPS requests by default.
import sys

SECURE_SSL_REDIRECT = (
    os.getenv("SECURE_SSL_REDIRECT", "True").lower() == "true"
    and not DEBUG
    and not TESTING
)

SESSION_COOKIE_SECURE = (
    os.getenv("SESSION_COOKIE_SECURE", "True").lower() == "true"
    and not TESTING
)

CSRF_COOKIE_SECURE = (
    os.getenv("CSRF_COOKIE_SECURE", "True").lower() == "true"
    and not TESTING
)

SESSION_COOKIE_HTTPONLY = True

SECURE_HSTS_SECONDS = (
    0 if IS_TESTING
    else int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = (
    False
    if TESTING
    else os.getenv(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS",
        "True",
    ).lower() == "true"
)

SECURE_HSTS_PRELOAD = (
    False
    if TESTING
    else os.getenv(
        "SECURE_HSTS_PRELOAD",
        "True",
    ).lower() == "true"
)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
# ---------------------------------------------------------
# Authentication / Owner dashboard
# ---------------------------------------------------------

# The owner dashboard is the only authenticated area
# exposed by this site.

LOGIN_URL = "owner:login"

LOGIN_REDIRECT_URL = "owner:dashboard"

LOGOUT_REDIRECT_URL = "core:home"


# ---------------------------------------------------------
# Natural May WhatsApp
# ---------------------------------------------------------

NATURALE_MAY_WHATSAPP = os.getenv(
    "NATURALE_MAY_WHATSAPP",
    "",
)


# ---------------------------------------------------------
# Default primary key
# ---------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
